num1 = input("Give me the first number: ")
num2 = input("Give me the second number: ")
print("Thank you!")
print(f"{num1} + {num2} = {int(num1) + int(num2)}")
print(f"{num1} - {num2} = {int(num1) - int(num2)}")
print(f"{num1} / {num2} = {int(int(num1) / int(num2))}")
print(f"{num1} * {num2} = {int(num1) * int(num2)}")